format = """
$directory \
$git_branch\
$git_status \
$character\
"""

[git_branch]
symbol = "â›“ "

[git_status]
#Gitã®ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹è¡¨ç¤ºç”¨ã‚¢ã‚¤ã‚³ãƒ³
conflicted = "ğŸ’¥"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ’­"
stashed = "ğŸ“¦"
modified = "ğŸ”"
staged = 'â¬†ï¸'
renamed = "ğŸ·"
deleted = "ğŸ—‘"

[character]
format = "ğŸ‘‰ "

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "â€¦/"