format = """
$directory\
$git_status \
$git_branch\
$character
"""

[git_branch]
format = "ï¼Š $branch "

[git_status]
format = "$conflicted$ahead$behind$diverged$untracked$stashed$modified$staged$renamed$deleted"
conflicted = " ğŸ’¥"
ahead = " âœ¨"
behind = " ğŸ˜°"
diverged = " ğŸ˜µ"
untracked = " ğŸ’­"
stashed = " ğŸ“¦"
modified = " â—"
staged = " ğŸ”¥"
renamed = " ğŸ·"
deleted = " ğŸ—‘"
up_to_date = " âœ…"

[character]
format = "ğŸ‘‰ "

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
truncation_length = 2
truncate_to_repo = false
truncation_symbol = "â€¦/"